= Parameters

The parent key for all of the following parameters is `kyverno`.

== `namespace`

[horizontal]
type:: string
default:: `syn-kyverno`

The namespace in which to deploy this component.


== `images`

[horizontal]
type:: dictionary

Dictionary containing the container images used by this component.


== `manifest_version`

[horizontal]
type:: string

The version of the kyverno manifests to download.

== `resourceFilters`

[horizontal]
type:: array

The admission webhook checks if a policy is applicable on all admission requests.
The Kubernetes kinds that shouldn't be processed.
`resourceFilters` must be a sequence of one or more `[<Kind>,<Namespace>,<Name>]`` entries with `*` as a wildcard. Thus, an item `[Node,*,*]` means that admissions of kind Node in any namespace and with any name will be ignored. Wildcards are also supported in each of these sequences.

For example, the sequence `[Pod,foo-system,redis*]` filters out kind Pod in namespace `foo-system` having names beginning with `redis`.

== `excludeGroupRole`

[horizontal]
type:: array

Exclude group roles from a user request.

== `generateSuccessEvents`

[horizontal]
type:: string
default:: `'false'`

Specifies whether (`true`/`false`) to generate success events.

== `extraArgs`

[horizontal]
type:: array
default:: `[]`
example::
+
[source,yaml]
----
extraArgs:
- -v=2
----

Allows passing extra arguments to Kyverno.

== `additionalClusterRoles`

[horizontal]
type:: object
default:: `{}`
example::
+
[source,yaml]
----
my-name:
  - <1>
    apiGroups:
      - rbac.authorization.k8s.io
    verbs:
      - '*'
    resources:
      - rolebindings
----
<1> The spec of the `rules` property within `ClusterRole` is taken verbatim.

Generates additional `ClusterRole`.
This is useful if you want to deploy Kyverno policies that generate resources, but the Kyverno ServiceAccount might have insufficient RBAC permissions to do so.

See also `additionalRoleBindings` to bind the Kyverno ServiceAccount to the new roles.

NOTE: The `metadata.name` is prefixed with `kyverno:user:` to avoid name clashes with existing resources.


== `additionalRoleBindings`

[horizontal]
type:: object
default:: `{}`
example::
+
[source,yaml]
----
allowManageRoleBindings: <1>
  kind: ClusterRole
  name: kyverno:user:my-name <2>
----
<1> This is the `metadata.name` of the RoleBinding.
<2> The name of the Role or ClusterRole to bind to.

Generates additional `ClusterRoleBinding` s in the Kyverno namespace for the Kyverno SystemAccount.
This is useful if you want to deploy Kyverno policies that generate resources in other namespaces, but the Kyverno ServiceAccount might have insufficient RBAC permissions to do so.

See also `additionalClusterRoles` if the necessary `ClusterRole` doesn't exist.

NOTE: The `metadata.name` is prefixed with `kyverno:user:` to avoid name clashes with existing resources.

TIP: If you need to reference a `ClusterRole` defined in `additionalClusterRoles`, you need to prefix the role name with `kyverno:user:` as shown in the example.

== `replicas`

[horizontal]
type:: int
default:: `3`

The amount of kyverno replicas.
Three or more replicas are required for high availability.

== `nodeSelectorRole`

[horizontal]
type:: enum
values:: `master`, `infra`, `null`
default:: `master`

The node role to run Kyverno pods on.
`null` equals no selector.

== `affinity`

[horizontal]
type:: string

Affinity configuration for the Kyverno pods.
See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#affinity-v1-core
